version: '3.8'

services:
  message-broker:
    image: rabbitmq:3.12.10
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - "4566:4566"
    restart: always

  resource-service:
    build:
      context: .
      dockerfile: ./ResourceService/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: "local"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  song-service:
    build:
      context: .
      dockerfile: ./SongService/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: "local"
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  discovery-service:
    build:
      context: .
      dockerfile: ./DiscoveryService/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: "local"
    ports:
      - "8082:8082"
    depends_on:
      - postgres